// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: api.proto

package proto

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ElectrocardiogramClient is the client API for Electrocardiogram service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ElectrocardiogramClient interface {
}

type electrocardiogramClient struct {
	cc grpc.ClientConnInterface
}

func NewElectrocardiogramClient(cc grpc.ClientConnInterface) ElectrocardiogramClient {
	return &electrocardiogramClient{cc}
}

// ElectrocardiogramServer is the server API for Electrocardiogram service.
// All implementations must embed UnimplementedElectrocardiogramServer
// for forward compatibility
type ElectrocardiogramServer interface {
	mustEmbedUnimplementedElectrocardiogramServer()
}

// UnimplementedElectrocardiogramServer must be embedded to have forward compatible implementations.
type UnimplementedElectrocardiogramServer struct {
}

func (UnimplementedElectrocardiogramServer) mustEmbedUnimplementedElectrocardiogramServer() {}

// UnsafeElectrocardiogramServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ElectrocardiogramServer will
// result in compilation errors.
type UnsafeElectrocardiogramServer interface {
	mustEmbedUnimplementedElectrocardiogramServer()
}

func RegisterElectrocardiogramServer(s grpc.ServiceRegistrar, srv ElectrocardiogramServer) {
	s.RegisterService(&Electrocardiogram_ServiceDesc, srv)
}

// Electrocardiogram_ServiceDesc is the grpc.ServiceDesc for Electrocardiogram service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Electrocardiogram_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Electrocardiogram",
	HandlerType: (*ElectrocardiogramServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api.proto",
}
